/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Inventory Management API
 * A comprehensive NestJS inventory and order management system with role-based access control, stock tracking, and audit logging.
 * OpenAPI spec version: 1.0
 */
export interface DashboardStatsDto {
  /** Total number of products */
  totalProducts: number;
  /** Number of active products */
  activeProducts: number;
  /** Number of low stock products */
  lowStockProducts: number;
  /** Total number of orders */
  totalOrders: number;
  /** Number of pending orders */
  pendingOrders: number;
  /** Number of completed orders */
  completedOrders: number;
  /** Total revenue from paid orders */
  totalRevenue: number;
  /** Revenue from today */
  todayRevenue: number;
  /** Total number of customers */
  totalCustomers: number;
}

export interface RevenueDataPointDto {
  /** Period label (month/day) */
  period: string;
  /** Revenue for this period */
  revenue: number;
  /** Number of orders in this period */
  orderCount: number;
}

export interface RevenueChartDto {
  /** Start date of the range */
  startDate: string;
  /** End date of the range */
  endDate: string;
  /** Grouping type (day, month, year) */
  groupBy: string;
  /** Total revenue in the range */
  totalRevenue: number;
  /** Total orders in the range */
  totalOrders: number;
  /** Revenue data points */
  data: RevenueDataPointDto[];
}

export interface LoginDto {
  /** User email address */
  email: string;
  /** User password */
  password: string;
}

export interface User {
  /** Unique identifier (UUID) */
  id: string;
  /** Full name of the user */
  name: string;
  /** Email address (unique) */
  email: string;
  /**
   * URL to user avatar image
   * @nullable
   */
  avatar: string | null;
  /** Whether the user account is active */
  isActive: boolean;
  /**
   * Timestamp of last login
   * @nullable
   */
  lastLogin: string | null;
  /** ID of the role assigned to this user */
  roleId: string;
  /** Timestamp when the user was created */
  createdAt: string;
  /** Timestamp when the user was last updated */
  updatedAt: string;
}

export interface AuthResponseDto {
  /** Authenticated user details */
  user: User;
  /** List of permission codes assigned to the user */
  permissions: string[];
  /** JWT access token (expires in 7 days) */
  accessToken: string;
  /** JWT refresh token (also sent as HTTP-only cookie) */
  refreshToken: string;
  /** Refresh token expiration date */
  refreshTokenExpires: string;
}

export interface RefreshTokenDto {
  /** Refresh token (optional if sent via cookie) */
  refreshToken?: string;
}

export interface ChangePasswordDto {
  /** Current password for verification */
  currentPassword: string;
  /**
   * New password (minimum 6 characters)
   * @minLength 6
   */
  newPassword: string;
}

export interface ProfileRoleDto {
  id: string;
  name: string;
  code: string;
}

/**
 * @nullable
 */
export type ProfileUserDtoAvatar = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type ProfileUserDtoLastLogin = { [key: string]: unknown } | null;

export interface ProfileUserDto {
  id: string;
  name: string;
  email: string;
  /** @nullable */
  avatar: ProfileUserDtoAvatar;
  isActive: boolean;
  /** @nullable */
  lastLogin: ProfileUserDtoLastLogin;
  role: ProfileRoleDto | null;
  createdAt: string;
  updatedAt: string;
}

export interface ProfileResponseDto {
  user: ProfileUserDto;
  /** List of permission codes assigned to the user */
  permissions: string[];
}

export interface ForgotPasswordDto {
  /** Email address to send password reset code */
  email: string;
}

export interface ResetPasswordDto {
  /** Email address associated with the reset code */
  email: string;
  /** Password reset code sent to email */
  code: string;
  /** New password (min 8 characters, must include uppercase, lowercase, number) */
  newPassword: string;
}

export interface CreateUserDto {
  /** Full name of the user */
  name: string;
  /** User email address (must be unique) */
  email: string;
  /**
   * User password (minimum 6 characters)
   * @minLength 6
   */
  password: string;
  /** UUID of the role to assign to the user */
  roleId: string;
}

export interface PaginatedUsersResponseDto {
  /** Array of users */
  data: User[];
  /** Total number of users */
  total: number;
  /** Current page number */
  page: number;
  /** Number of items per page */
  limit: number;
}

export interface UpdateUserDto {
  /** Full name of the user */
  name?: string;
  /** User email address */
  email?: string;
  /** UUID of the role to assign to the user */
  roleId?: string;
}

export interface CreateRoleDto {
  /** Display name of the role */
  name: string;
  /** Unique code identifier for the role (lowercase with underscores) */
  code: string;
  /** Array of permission IDs to assign to the role */
  permissionIds?: string[];
}

export interface Permission {
  /** Unique identifier (UUID) */
  id: string;
  /** Display name of the permission */
  name: string;
  /** Unique system identifier for the permission */
  code: string;
  /** Timestamp when the permission was created */
  createdAt: string;
}

export interface RoleWithPermissionsDto {
  /** Role ID */
  id: string;
  /** Role name */
  name: string;
  /** Role code */
  code: string;
  /** Creation timestamp */
  createdAt: string;
  /** Permissions assigned to this role */
  permissions: Permission[];
}

export interface PaginatedRolesResponseDto {
  /** Array of roles with permissions */
  data: RoleWithPermissionsDto[];
  /** Total number of roles */
  total: number;
  /** Current page number */
  page: number;
  /** Number of items per page */
  limit: number;
}

export interface UpdateRoleDto {
  /** Display name of the role */
  name?: string;
  /** Description of the role responsibilities */
  description?: string;
}

export interface AssignPermissionsDto {
  /** Array of permission UUIDs to assign to the role (replaces existing permissions) */
  permissionIds: string[];
}

export interface CreatePermissionDto {
  /** Display name of the permission */
  name: string;
  /** Unique permission code (format: resource:action) */
  code: string;
}

export interface PaginatedPermissionsResponseDto {
  /** Array of permissions */
  data: Permission[];
  /** Total number of permissions */
  total: number;
  /** Current page number */
  page: number;
  /** Number of items per page */
  limit: number;
}

/**
 * Module this permission belongs to
 */
export type UpdatePermissionDtoModule = typeof UpdatePermissionDtoModule[keyof typeof UpdatePermissionDtoModule];


export const UpdatePermissionDtoModule = {
  inventory: 'inventory',
  orders: 'orders',
  stock: 'stock',
  users: 'users',
  reports: 'reports',
  settings: 'settings',
  customers: 'customers',
  staff: 'staff',
  roles: 'roles',
  permissions: 'permissions',
} as const;

/**
 * Action type
 */
export type UpdatePermissionDtoAction = typeof UpdatePermissionDtoAction[keyof typeof UpdatePermissionDtoAction];


export const UpdatePermissionDtoAction = {
  create: 'create',
  read: 'read',
  update: 'update',
  delete: 'delete',
  confirm: 'confirm',
  complete: 'complete',
  cancel: 'cancel',
} as const;

export interface UpdatePermissionDto {
  /** Display name of the permission */
  name?: string;
  /** Module this permission belongs to */
  module?: UpdatePermissionDtoModule;
  /** Action type */
  action?: UpdatePermissionDtoAction;
}

export interface CreateStaffDto {
  /** User ID to link staff profile to */
  userId?: string;
  /** Department */
  department?: string;
  /** Position/Job Title */
  position?: string;
  /** Hire date (ISO 8601) */
  hireDate?: string;
  /** Additional notes */
  notes?: string;
}

/**
 * Department
 * @nullable
 */
export type StaffDepartment = { [key: string]: unknown } | null;

/**
 * Position/Job Title
 * @nullable
 */
export type StaffPosition = { [key: string]: unknown } | null;

/**
 * Hire date
 * @nullable
 */
export type StaffHireDate = { [key: string]: unknown } | null;

/**
 * Additional notes
 * @nullable
 */
export type StaffNotes = { [key: string]: unknown } | null;

export interface Staff {
  /** Unique identifier (UUID) */
  id: string;
  /** Employee ID */
  employeeId: string;
  /** User ID (links to User account) */
  userId: string;
  /**
   * Department
   * @nullable
   */
  department: StaffDepartment;
  /**
   * Position/Job Title
   * @nullable
   */
  position: StaffPosition;
  /**
   * Hire date
   * @nullable
   */
  hireDate: StaffHireDate;
  /** Whether the staff member is active */
  isActive: boolean;
  /**
   * Additional notes
   * @nullable
   */
  notes: StaffNotes;
  /** Timestamp when the staff record was created */
  createdAt: string;
  /** Timestamp when the staff record was last updated */
  updatedAt: string;
}

export interface PaginatedStaffResponseDto {
  /** List of staff members */
  data: Staff[];
  /** Total number of staff members */
  total: number;
  /** Current page number */
  page: number;
  /** Number of items per page */
  limit: number;
  /** Total number of pages */
  totalPages: number;
}

export interface UpdateStaffDto {
  /** User ID to link staff profile to */
  userId?: string;
  /** Department */
  department?: string;
  /** Position/Job Title */
  position?: string;
  /** Hire date (ISO 8601) */
  hireDate?: string;
  /** Additional notes */
  notes?: string;
  /** Whether the staff member is active */
  isActive?: boolean;
}

/**
 * User who performed the action
 * @nullable
 */
export type AuditLogUserId = { [key: string]: unknown } | null;

/**
 * Action performed
 */
export type AuditLogAction = typeof AuditLogAction[keyof typeof AuditLogAction];


export const AuditLogAction = {
  create: 'create',
  update: 'update',
  delete: 'delete',
  login: 'login',
  logout: 'logout',
  login_failed: 'login_failed',
  password_reset: 'password_reset',
  email_verified: 'email_verified',
  role_assigned: 'role_assigned',
  permission_granted: 'permission_granted',
  permission_revoked: 'permission_revoked',
  order_confirmed: 'order_confirmed',
  order_paid: 'order_paid',
  order_completed: 'order_completed',
  order_cancelled: 'order_cancelled',
  stock_adjusted: 'stock_adjusted',
  export: 'export',
  import: 'import',
} as const;

/**
 * Module where action occurred
 */
export type AuditLogModule = typeof AuditLogModule[keyof typeof AuditLogModule];


export const AuditLogModule = {
  auth: 'auth',
  users: 'users',
  roles: 'roles',
  permissions: 'permissions',
  staff: 'staff',
  customers: 'customers',
  orders: 'orders',
  products: 'products',
  categories: 'categories',
  stock: 'stock',
  settings: 'settings',
  reports: 'reports',
} as const;

/**
 * ID of the affected entity
 * @nullable
 */
export type AuditLogEntityId = { [key: string]: unknown } | null;

/**
 * Changes made (before/after values)
 * @nullable
 */
export type AuditLogChanges = { [key: string]: unknown } | null;

/**
 * IP address of the user
 * @nullable
 */
export type AuditLogIpAddress = { [key: string]: unknown } | null;

/**
 * User agent string
 * @nullable
 */
export type AuditLogUserAgent = { [key: string]: unknown } | null;

/**
 * Additional metadata
 * @nullable
 */
export type AuditLogMetadata = { [key: string]: unknown } | null;

/**
 * Description of the action
 */
export type AuditLogDescription = { [key: string]: unknown };

export interface AuditLog {
  /** Unique identifier */
  id: string;
  /**
   * User who performed the action
   * @nullable
   */
  userId: AuditLogUserId;
  /** Action performed */
  action: AuditLogAction;
  /** Module where action occurred */
  module: AuditLogModule;
  /** Entity type (e.g., Order, User, Product) */
  entity: string;
  /**
   * ID of the affected entity
   * @nullable
   */
  entityId: AuditLogEntityId;
  /**
   * Changes made (before/after values)
   * @nullable
   */
  changes: AuditLogChanges;
  /**
   * IP address of the user
   * @nullable
   */
  ipAddress: AuditLogIpAddress;
  /**
   * User agent string
   * @nullable
   */
  userAgent: AuditLogUserAgent;
  /**
   * Additional metadata
   * @nullable
   */
  metadata: AuditLogMetadata;
  /** Description of the action */
  description: AuditLogDescription;
  /** Timestamp of the action */
  createdAt: string;
}

export interface PaginatedAuditLogsResponseDto {
  data: AuditLog[];
  /** Total number of audit logs */
  total: number;
  /** Current page number */
  page: number;
  /** Number of items per page */
  limit: number;
  /** Total number of pages */
  totalPages: number;
}

export interface CreateProductDto {
  /** Product SKU (Stock Keeping Unit) */
  sku: string;
  /** Product name */
  name: string;
  /** Product description */
  description?: string;
  /** Category ID */
  categoryId?: string;
  /** Brand ID */
  brandId?: string;
  /** Manufacturer ID */
  manufacturerId?: string;
  /** Product unit of measurement */
  unit?: string;
  /** Cost price per unit */
  costPrice: number;
  /** Selling price per unit */
  sellingPrice: number;
  /** Whether to track inventory for this product */
  trackInventory?: boolean;
  /** Initial stock quantity (only used if trackInventory is true) */
  initialStock?: number;
  /** Minimum stock level for alerts */
  minimumStock?: number;
  /** Product image URL */
  imageUrl?: string;
  /** Barcode number */
  barcode?: string;
  /** Additional notes */
  notes?: string;
  /** Whether the product is active */
  isActive?: boolean;
}

export interface CategoryResponseDto {
  id: string;
  code: string;
  name: string;
}

export interface BrandResponseDto {
  id: string;
  name: string;
}

export interface ManufacturerResponseDto {
  id: string;
  name: string;
}

export interface ProductInventoryDto {
  quantity: number;
  minimumStock: number;
}

/**
 * @nullable
 */
export type VariantResponseDtoImageUrl = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type VariantResponseDtoBarcode = { [key: string]: unknown } | null;

export interface VariantResponseDto {
  id: string;
  sku: string;
  name: string;
  costPrice: number;
  sellingPrice: number;
  isActive: boolean;
  /** @nullable */
  imageUrl: VariantResponseDtoImageUrl;
  /** @nullable */
  barcode: VariantResponseDtoBarcode;
  inventory: ProductInventoryDto | null;
}

/**
 * @nullable
 */
export type ProductResponseDtoDescription = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type ProductResponseDtoUnit = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type ProductResponseDtoImageUrl = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type ProductResponseDtoBarcode = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type ProductResponseDtoNotes = { [key: string]: unknown } | null;

/**
 * Total stock across all variants (only present when hasVariants is true)
 * @nullable
 */
export type ProductResponseDtoTotalStock = { [key: string]: unknown } | null;

export interface ProductResponseDto {
  id: string;
  sku: string;
  name: string;
  /** @nullable */
  description: ProductResponseDtoDescription;
  costPrice: number;
  sellingPrice: number;
  /** @nullable */
  unit: ProductResponseDtoUnit;
  trackInventory: boolean;
  isActive: boolean;
  hasVariants: boolean;
  /** @nullable */
  imageUrl: ProductResponseDtoImageUrl;
  /** @nullable */
  barcode: ProductResponseDtoBarcode;
  /** @nullable */
  notes: ProductResponseDtoNotes;
  category: CategoryResponseDto | null;
  brand: BrandResponseDto | null;
  manufacturer: ManufacturerResponseDto | null;
  /** Inventory info (null when hasVariants is true) */
  inventory: ProductInventoryDto | null;
  /**
   * Variants array (only present when hasVariants is true)
   * @nullable
   */
  variants: VariantResponseDto[] | null;
  /**
   * Total stock across all variants (only present when hasVariants is true)
   * @nullable
   */
  totalStock: ProductResponseDtoTotalStock;
  createdAt: string;
  updatedAt: string;
}

export interface CsvRowErrorDto {
  /** Row number in CSV (1-indexed, excluding header) */
  row: number;
  /** SKU from the row (if available) */
  sku: string;
  /** List of validation errors for this row */
  errors: string[];
}

export interface CsvUploadResultDto {
  /** Total number of data rows in CSV */
  totalRows: number;
  /** Number of products successfully created */
  created: number;
  /** Number of rows that failed validation */
  failed: number;
  /** Detailed errors for failed rows */
  errors: CsvRowErrorDto[];
}

export interface PaginatedProductsResponseDto {
  /** Array of products */
  data: ProductResponseDto[];
  /** Total number of products */
  total: number;
  /** Current page number */
  page: number;
  /** Number of items per page */
  limit: number;
}

export interface LowStockProductDto {
  /** Product ID */
  id: string;
  /** Product SKU */
  sku: string;
  /** Product name */
  name: string;
  /** Current stock quantity */
  stockQuantity: number;
  /** Minimum stock level */
  minimumStock: number;
  /** Stock deficit */
  deficit: number;
}

export interface UpdateProductDto {
  /** Product SKU (Stock Keeping Unit) */
  sku?: string;
  /** Product name */
  name?: string;
  /** Product description */
  description?: string;
  /** Category ID */
  categoryId?: string;
  /** Brand ID */
  brandId?: string;
  /** Manufacturer ID */
  manufacturerId?: string;
  /** Product unit of measurement */
  unit?: string;
  /** Cost price per unit */
  costPrice?: number;
  /** Selling price per unit */
  sellingPrice?: number;
  /** Whether to track inventory for this product */
  trackInventory?: boolean;
  /** Initial stock quantity (only used if trackInventory is true) */
  initialStock?: number;
  /** Minimum stock level for alerts */
  minimumStock?: number;
  /** Product image URL */
  imageUrl?: string;
  /** Barcode number */
  barcode?: string;
  /** Additional notes */
  notes?: string;
  /** Whether the product is active */
  isActive?: boolean;
}

/**
 * Variant barcode
 * @nullable
 */
export type ProductVariantBarcode = { [key: string]: unknown } | null;

/**
 * Variant-specific image URL
 * @nullable
 */
export type ProductVariantImageUrl = { [key: string]: unknown } | null;

export interface ProductVariant {
  /** Unique identifier (UUID) */
  id: string;
  /** Parent product ID */
  productId: string;
  /** Variant name (e.g., "RED XL", "BLUE M") */
  name: string;
  /** Variant SKU */
  sku: string;
  /**
   * Variant barcode
   * @nullable
   */
  barcode: ProductVariantBarcode;
  /** Cost price per unit */
  costPrice: number;
  /** Selling price per unit */
  sellingPrice: number;
  /**
   * Variant-specific image URL
   * @nullable
   */
  imageUrl: ProductVariantImageUrl;
  /** Whether the variant is active */
  isActive: boolean;
  /** Timestamp when the variant was created */
  createdAt: string;
}

export interface CreateVariantDto {
  /** Variant name (e.g., "RED XL", "BLUE M") */
  name: string;
  /** Variant SKU */
  sku: string;
  /** Variant barcode */
  barcode?: string;
  /** Cost price */
  costPrice: number;
  /** Selling price */
  sellingPrice: number;
  /** Initial stock quantity */
  initialStock?: number;
  /** Minimum stock level */
  minimumStock?: number;
  /** Variant image URL */
  imageUrl?: string;
}

export interface UpdateVariantDto {
  /** Variant name (e.g., "RED XL", "BLUE M") */
  name?: string;
  /** Variant SKU */
  sku?: string;
  /** Variant barcode */
  barcode?: string;
  /** Cost price */
  costPrice?: number;
  /** Selling price */
  sellingPrice?: number;
  /** Initial stock quantity */
  initialStock?: number;
  /** Minimum stock level */
  minimumStock?: number;
  /** Variant image URL */
  imageUrl?: string;
}

export interface CreateCategoryDto {
  /** Category name */
  name: string;
  /** Category code/slug */
  code: string;
  /** Category description */
  description?: string;
  /** Whether the category is active */
  isActive?: boolean;
}

/**
 * Category description
 * @nullable
 */
export type CategoryDescription = { [key: string]: unknown } | null;

export interface Category {
  /** Unique identifier (UUID) */
  id: string;
  /** Category name */
  name: string;
  /** Category code/slug */
  code: string;
  /**
   * Category description
   * @nullable
   */
  description: CategoryDescription;
  /** Whether the category is active */
  isActive: boolean;
  /** Timestamp when the category was created */
  createdAt: string;
  /** Timestamp when the category was last updated */
  updatedAt: string;
}

export interface UpdateCategoryDto {
  /** Category name */
  name?: string;
  /** Category code/slug */
  code?: string;
  /** Category description */
  description?: string;
  /** Whether the category is active */
  isActive?: boolean;
}

export interface CreateBrandDto {
  /** Brand name */
  name: string;
}

export interface Brand {
  /** Unique identifier (UUID) */
  id: string;
  /** Brand name */
  name: string;
  /** Timestamp when the brand was created */
  createdAt: string;
}

export interface CreateManufacturerDto {
  /** Manufacturer name */
  name: string;
}

export interface Manufacturer {
  /** Unique identifier (UUID) */
  id: string;
  /** Manufacturer name */
  name: string;
  /** Timestamp when the manufacturer was created */
  createdAt: string;
}

export interface ProductSummaryDto {
  id: string;
  sku: string;
  name: string;
}

export interface VariantSummaryDto {
  id: string;
  sku: string;
  name: string;
}

export interface InventoryResponseDto {
  id: string;
  quantity: number;
  minimumStock: number;
  product: ProductSummaryDto;
  variant: VariantSummaryDto | null;
  createdAt: string;
  updatedAt: string;
}

export interface PaginatedInventoryDataDto {
  items: InventoryResponseDto[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface LowStockItemDto {
  id: string;
  quantity: number;
  minimumStock: number;
  /** How much below minimum stock */
  deficit: number;
  product: ProductSummaryDto;
  variant: VariantSummaryDto | null;
}

export interface PaginatedLowStockDataDto {
  items: LowStockItemDto[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface InventoryResponseWrapperDto {
  message: string;
  data: InventoryResponseDto;
}

export interface InventoryArrayResponseWrapperDto {
  message: string;
  data: InventoryResponseDto[];
}

export interface UpdateInventoryDto {
  /** Minimum stock level */
  minimumStock?: number;
}

/**
 * Type of adjustment
 */
export type AdjustInventoryDtoType = typeof AdjustInventoryDtoType[keyof typeof AdjustInventoryDtoType];


export const AdjustInventoryDtoType = {
  ADD: 'ADD',
  REMOVE: 'REMOVE',
  SET: 'SET',
} as const;

export interface AdjustInventoryDto {
  /** Type of adjustment */
  type: AdjustInventoryDtoType;
  /** Quantity to adjust */
  quantity: number;
  /** Reason for adjustment */
  reason?: string;
  /** Type of reference (order, manual, return) */
  referenceType?: string;
  /** ID of the referenced entity */
  referenceId?: string;
}

/**
 * @nullable
 */
export type UserSummaryDtoName = { [key: string]: unknown } | null;

export interface UserSummaryDto {
  id: string;
  email: string;
  /** @nullable */
  name: UserSummaryDtoName;
}

export type InventoryTransactionResponseDtoType = typeof InventoryTransactionResponseDtoType[keyof typeof InventoryTransactionResponseDtoType];


export const InventoryTransactionResponseDtoType = {
  ADD: 'ADD',
  REMOVE: 'REMOVE',
  SET: 'SET',
} as const;

/**
 * @nullable
 */
export type InventoryTransactionResponseDtoReason = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type InventoryTransactionResponseDtoReferenceType = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type InventoryTransactionResponseDtoReferenceId = { [key: string]: unknown } | null;

export interface InventoryTransactionResponseDto {
  id: string;
  type: InventoryTransactionResponseDtoType;
  quantity: number;
  previousQuantity: number;
  newQuantity: number;
  /** @nullable */
  reason: InventoryTransactionResponseDtoReason;
  /** @nullable */
  referenceType: InventoryTransactionResponseDtoReferenceType;
  /** @nullable */
  referenceId: InventoryTransactionResponseDtoReferenceId;
  creator: UserSummaryDto | null;
  createdAt: string;
}

export interface PaginatedTransactionsDataDto {
  items: InventoryTransactionResponseDto[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface PaginatedTransactionsResponseDto {
  message: string;
  data: PaginatedTransactionsDataDto;
}

/**
 * Customer type
 */
export type RegisterCustomerDtoCustomerType = typeof RegisterCustomerDtoCustomerType[keyof typeof RegisterCustomerDtoCustomerType];


export const RegisterCustomerDtoCustomerType = {
  'walk-in': 'walk-in',
  regular: 'regular',
  wholesale: 'wholesale',
} as const;

export interface RegisterCustomerDto {
  /** Full name */
  name: string;
  /** Email address */
  email: string;
  /** Password (minimum 8 characters, 1 uppercase, 1 lowercase, 1 number) */
  password: string;
  /** Phone number */
  phone?: string;
  /** Customer type */
  customerType?: RegisterCustomerDtoCustomerType;
}

/**
 * Customer type
 */
export type CreateCustomerDtoCustomerType = typeof CreateCustomerDtoCustomerType[keyof typeof CreateCustomerDtoCustomerType];


export const CreateCustomerDtoCustomerType = {
  'walk-in': 'walk-in',
  regular: 'regular',
  wholesale: 'wholesale',
} as const;

export interface CreateCustomerDto {
  /** Customer name */
  name: string;
  /** Email address */
  email?: string;
  /** Phone number */
  phone?: string;
  /** Customer type */
  customerType?: CreateCustomerDtoCustomerType;
  /** User ID to link to existing user */
  userId?: string;
  /** Additional notes */
  notes?: string;
}

/**
 * Phone number
 * @nullable
 */
export type CustomerPhone = { [key: string]: unknown } | null;

/**
 * Customer type
 */
export type CustomerCustomerType = typeof CustomerCustomerType[keyof typeof CustomerCustomerType];


export const CustomerCustomerType = {
  'walk-in': 'walk-in',
  regular: 'regular',
  wholesale: 'wholesale',
} as const;

/**
 * Additional notes
 * @nullable
 */
export type CustomerNotes = { [key: string]: unknown } | null;

export interface Customer {
  /** Unique identifier (UUID) */
  id: string;
  /** Customer number */
  customerNumber: string;
  /** Customer name */
  name: string;
  /** Email address */
  email: string;
  /**
   * Phone number
   * @nullable
   */
  phone: CustomerPhone;
  /** Customer type */
  customerType: CustomerCustomerType;
  /** User ID (links to User account for login) */
  userId: string;
  /** Whether email has been verified */
  isEmailVerified: boolean;
  /**
   * Additional notes
   * @nullable
   */
  notes: CustomerNotes;
  /** Whether the customer is active */
  isActive: boolean;
  /** Timestamp when the customer was created */
  createdAt: string;
  /** Timestamp when the customer was last updated */
  updatedAt: string;
}

export interface PaginatedCustomersResponseDto {
  /** List of customers */
  data: Customer[];
  /** Total number of customers */
  total: number;
  /** Current page number */
  page: number;
  /** Number of items per page */
  limit: number;
  /** Total number of pages */
  totalPages: number;
}

/**
 * Customer type
 */
export type UpdateCustomerDtoCustomerType = typeof UpdateCustomerDtoCustomerType[keyof typeof UpdateCustomerDtoCustomerType];


export const UpdateCustomerDtoCustomerType = {
  'walk-in': 'walk-in',
  regular: 'regular',
  wholesale: 'wholesale',
} as const;

export interface UpdateCustomerDto {
  /** Customer name */
  name?: string;
  /** Email address */
  email?: string;
  /** Phone number */
  phone?: string;
  /** Customer type */
  customerType?: UpdateCustomerDtoCustomerType;
  /** User ID to link to existing user */
  userId?: string;
  /** Additional notes */
  notes?: string;
}

/**
 * Address type
 */
export type CreateAddressDtoAddressType = typeof CreateAddressDtoAddressType[keyof typeof CreateAddressDtoAddressType];


export const CreateAddressDtoAddressType = {
  billing: 'billing',
  shipping: 'shipping',
  both: 'both',
} as const;

export interface CreateAddressDto {
  /** Street address */
  street: string;
  /** City */
  city: string;
  /** State/Province */
  state: string;
  /** Postal code */
  postalCode: string;
  /** Country */
  country: string;
  /** Address type */
  addressType: CreateAddressDtoAddressType;
  /** Set as default address */
  isDefault?: boolean;
}

/**
 * Address type
 */
export type CustomerAddressAddressType = typeof CustomerAddressAddressType[keyof typeof CustomerAddressAddressType];


export const CustomerAddressAddressType = {
  billing: 'billing',
  shipping: 'shipping',
  both: 'both',
} as const;

export interface CustomerAddress {
  /** Unique identifier (UUID) */
  id: string;
  /** Customer ID */
  customerId: string;
  /** Street address */
  street: string;
  /** City */
  city: string;
  /** State/Province */
  state: string;
  /** Postal code */
  postalCode: string;
  /** Country */
  country: string;
  /** Address type */
  addressType: CustomerAddressAddressType;
  /** Whether this is the default address */
  isDefault: boolean;
  /** Timestamp when the address was created */
  createdAt: string;
  /** Timestamp when the address was last updated */
  updatedAt: string;
}

export interface CreateOrderItemDto {
  /** Product ID */
  productId: string;
  /** Variant ID (required for products with variants) */
  variantId?: string;
  /**
   * Quantity to order
   * @minimum 1
   */
  quantity: number;
  /** Unit price (optional override, defaults to product selling price) */
  unitPrice?: number;
}

/**
 * Order type
 */
export type CreateOrderDtoOrderType = typeof CreateOrderDtoOrderType[keyof typeof CreateOrderDtoOrderType];


export const CreateOrderDtoOrderType = {
  online: 'online',
  pos: 'pos',
  phone: 'phone',
} as const;

/**
 * Payment method
 */
export type CreateOrderDtoPaymentMethod = typeof CreateOrderDtoPaymentMethod[keyof typeof CreateOrderDtoPaymentMethod];


export const CreateOrderDtoPaymentMethod = {
  cash: 'cash',
  bank_transfer: 'bank_transfer',
  online: 'online',
  credit: 'credit',
} as const;

export interface CreateOrderDto {
  /** Customer ID (optional for POS walk-in orders) */
  customerId?: string;
  /** Order type */
  orderType?: CreateOrderDtoOrderType;
  /** Receipt number (for POS orders) */
  receiptNumber?: string;
  /**
   * Order items
   * @minItems 1
   */
  items: CreateOrderItemDto[];
  /** Discount amount */
  discount?: number;
  /** Tax amount */
  tax?: number;
  /** Payment method */
  paymentMethod?: CreateOrderDtoPaymentMethod;
  /** Additional notes */
  notes?: string;
}

/**
 * Customer ID (optional for POS orders)
 * @nullable
 */
export type OrderCustomerId = { [key: string]: unknown } | null;

/**
 * Order status
 */
export type OrderStatus = typeof OrderStatus[keyof typeof OrderStatus];


export const OrderStatus = {
  pending: 'pending',
  confirmed: 'confirmed',
  completed: 'completed',
  cancelled: 'cancelled',
} as const;

/**
 * Order type (online, pos, phone)
 */
export type OrderOrderType = typeof OrderOrderType[keyof typeof OrderOrderType];


export const OrderOrderType = {
  online: 'online',
  pos: 'pos',
  phone: 'phone',
} as const;

/**
 * Receipt number (for POS orders)
 * @nullable
 */
export type OrderReceiptNumber = { [key: string]: unknown } | null;

/**
 * Payment method
 * @nullable
 */
export type OrderPaymentMethod = typeof OrderPaymentMethod[keyof typeof OrderPaymentMethod] | null;


export const OrderPaymentMethod = {
  cash: 'cash',
  bank_transfer: 'bank_transfer',
  online: 'online',
  credit: 'credit',
} as const;

/**
 * Discount amount
 * @nullable
 */
export type OrderDiscount = { [key: string]: unknown } | null;

/**
 * Tax amount
 * @nullable
 */
export type OrderTax = { [key: string]: unknown } | null;

/**
 * Additional notes
 * @nullable
 */
export type OrderNotes = { [key: string]: unknown } | null;

export interface Order {
  /** Unique identifier (UUID) */
  id: string;
  /** Order number */
  orderNumber: string;
  /**
   * Customer ID (optional for POS orders)
   * @nullable
   */
  customerId: OrderCustomerId;
  /** Order status */
  status: OrderStatus;
  /** Order type (online, pos, phone) */
  orderType: OrderOrderType;
  /**
   * Receipt number (for POS orders)
   * @nullable
   */
  receiptNumber: OrderReceiptNumber;
  /** Whether the order is paid */
  isPaid: boolean;
  /**
   * Payment method
   * @nullable
   */
  paymentMethod: OrderPaymentMethod;
  /** Total amount */
  totalAmount: number;
  /**
   * Discount amount
   * @nullable
   */
  discount: OrderDiscount;
  /**
   * Tax amount
   * @nullable
   */
  tax: OrderTax;
  /**
   * Additional notes
   * @nullable
   */
  notes: OrderNotes;
  /** ID of user who created this order */
  createdBy: string;
  /** Timestamp when the order was created */
  createdAt: string;
  /** Timestamp when the order was last updated */
  updatedAt: string;
}

export interface PaginatedOrdersResponseDto {
  /** List of orders */
  data: Order[];
  /** Total number of orders */
  total: number;
  /** Current page number */
  page: number;
  /** Number of items per page */
  limit: number;
  /** Total number of pages */
  totalPages: number;
}

export interface UpdateOrderDto {
  /** Discount amount */
  discount?: number;
  /** Tax amount */
  tax?: number;
  /** Additional notes */
  notes?: string;
}

/**
 * Payment method
 */
export type MarkOrderPaidDtoPaymentMethod = typeof MarkOrderPaidDtoPaymentMethod[keyof typeof MarkOrderPaidDtoPaymentMethod];


export const MarkOrderPaidDtoPaymentMethod = {
  cash: 'cash',
  bank_transfer: 'bank_transfer',
  online: 'online',
  credit: 'credit',
} as const;

export interface MarkOrderPaidDto {
  /** Payment method */
  paymentMethod: MarkOrderPaidDtoPaymentMethod;
  /** Transaction reference (for bank transfers, online payments) */
  transactionReference?: string;
}

export type AnalyticsControllerGetRevenueChartParams = {
/**
 * Start date (YYYY-MM-DD format). Defaults to 30 days ago.
 */
startDate?: string;
/**
 * End date (YYYY-MM-DD format). Defaults to today.
 */
endDate?: string;
};

export type UsersControllerFindAllParams = {
page?: number;
limit?: number;
};

export type RolesControllerFindAllRolesParams = {
page?: number;
limit?: number;
};

export type PermissionsControllerFindAllPermissionsParams = {
page?: number;
limit?: number;
};

export type StaffControllerFindAllParams = {
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 */
limit?: number;
/**
 * Filter by department
 */
department?: string;
/**
 * Include inactive staff members
 */
includeInactive?: boolean;
};

export type AuditLogsControllerFindAllParams = {
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 */
limit?: number;
/**
 * Filter by user ID
 */
userId?: string;
/**
 * Filter by action
 */
action?: AuditLogsControllerFindAllAction;
/**
 * Filter by module
 */
module?: AuditLogsControllerFindAllModule;
/**
 * Filter by entity type
 */
entity?: string;
/**
 * Filter by entity ID
 */
entityId?: string;
/**
 * Filter by start date (ISO 8601)
 */
startDate?: string;
/**
 * Filter by end date (ISO 8601)
 */
endDate?: string;
};

export type AuditLogsControllerFindAllAction = typeof AuditLogsControllerFindAllAction[keyof typeof AuditLogsControllerFindAllAction];


export const AuditLogsControllerFindAllAction = {
  create: 'create',
  update: 'update',
  delete: 'delete',
  login: 'login',
  logout: 'logout',
  login_failed: 'login_failed',
  password_reset: 'password_reset',
  email_verified: 'email_verified',
  role_assigned: 'role_assigned',
  permission_granted: 'permission_granted',
  permission_revoked: 'permission_revoked',
  order_confirmed: 'order_confirmed',
  order_paid: 'order_paid',
  order_completed: 'order_completed',
  order_cancelled: 'order_cancelled',
  stock_adjusted: 'stock_adjusted',
  export: 'export',
  import: 'import',
} as const;

export type AuditLogsControllerFindAllModule = typeof AuditLogsControllerFindAllModule[keyof typeof AuditLogsControllerFindAllModule];


export const AuditLogsControllerFindAllModule = {
  auth: 'auth',
  users: 'users',
  roles: 'roles',
  permissions: 'permissions',
  staff: 'staff',
  customers: 'customers',
  orders: 'orders',
  products: 'products',
  categories: 'categories',
  stock: 'stock',
  settings: 'settings',
  reports: 'reports',
} as const;

export type AuditLogsControllerFindByEntityParams = {
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 */
limit?: number;
};

export type AuditLogsControllerFindByUserParams = {
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 */
limit?: number;
};

export type AuditLogsControllerGetStatisticsParams = {
/**
 * Filter by start date (ISO 8601)
 */
startDate?: string;
/**
 * Filter by end date (ISO 8601)
 */
endDate?: string;
};

export type ProductsControllerFindAllParams = {
page?: number;
limit?: number;
/**
 * Filter by category ID
 */
categoryId?: string;
/**
 * Search by name, SKU, or barcode
 */
search?: string;
includeInactive?: boolean;
};

export type CsvFileUploadDto = {
  /** CSV file to upload */
  file: Blob;
};

export type CsvVariantFileUploadDto = {
  /** CSV file containing variant data to upload */
  file: Blob;
};

export type CategoriesControllerFindAllParams = {
page?: number;
limit?: number;
includeInactive?: boolean;
};

export type InventoryControllerFindAllParams = {
page?: number;
limit?: number;
};

export type InventoryControllerGetLowStockParams = {
page?: number;
limit?: number;
};

export type InventoryControllerGetTransactionsParams = {
page?: number;
limit?: number;
};

export type CustomersControllerVerifyEmailParams = {
/**
 * Verification token
 */
token: string;
};

export type CustomersControllerFindAllParams = {
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 */
limit?: number;
/**
 * Filter by customer type
 */
customerType?: string;
/**
 * Search by name, email, phone, or customer number
 */
search?: string;
/**
 * Include inactive customers
 */
includeInactive?: boolean;
};

export type OrdersControllerFindAllParams = {
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 */
limit?: number;
/**
 * Filter by order status
 */
status?: OrdersControllerFindAllStatus;
/**
 * Filter by customer ID
 */
customerId?: string;
/**
 * Filter by start date (ISO 8601)
 */
startDate?: string;
/**
 * Filter by end date (ISO 8601)
 */
endDate?: string;
/**
 * Filter by payment status
 */
isPaid?: boolean;
/**
 * Filter by order type (online, pos, phone)
 */
orderType?: OrdersControllerFindAllOrderType;
};

export type OrdersControllerFindAllStatus = typeof OrdersControllerFindAllStatus[keyof typeof OrdersControllerFindAllStatus];


export const OrdersControllerFindAllStatus = {
  pending: 'pending',
  confirmed: 'confirmed',
  completed: 'completed',
  cancelled: 'cancelled',
} as const;

export type OrdersControllerFindAllOrderType = typeof OrdersControllerFindAllOrderType[keyof typeof OrdersControllerFindAllOrderType];


export const OrdersControllerFindAllOrderType = {
  online: 'online',
  pos: 'pos',
  phone: 'phone',
} as const;

